### ISSUE TITLE
サイト調査

### ISSUE THREAD

**Issue by eteRnaL198** [kikudesuyo/price-comparison#1]
# やること
- ECサイトのDOM(HTMLの要素)を調べて、何を抜き出せばいいのか見る
- 必要な情報
  - 画像
  - 商品名
  - 値段(送料)
- Issueのコメントにまとめる
# やりかた
- ctrl + shift + i で開発者ツールを開く
-  elements を開く
- 左上にあるカーソルボタンを押す
-  必要な要素のtagをまとめる

**Comment by kikudesuyo** [comment]
# 必要な要素のtag
- Amazon
  - 値段
  ```<span class="a-price-whole">745</span>```
  - 商品名
  ```<span id="productTitle" class="a-size-large product-title-word-break"> シュアラスター 洗車用品 カーシャンプー ノーコンパウンド 1000ml S-30 中性 防錆剤配合 </span> ```
 - 画像
 ```<img src="https://m.media-amazon.com/images/I/91KkPzNj4JL._AC_SY355_.jpg" class="a-dynamic-image" id="" style="max-height: 271px; max-width: 271px;" data-old-hires="https://m.media-amazon.com/images/I/91KkPzNj4JL._AC_SL1500_.jpg" data-a-manual-replacement="true">```
