### ISSUE TITLE
matplotlibでグラフ描画

### ISSUE THREAD

**Issue by eteRnaL198** [kikudesuyo/price-comparison#9]
# やること
- matplotlibでグラフを描画する
  - ASIN.dat内のデータを読み込む
  - タイトル: 商品名
  - どっかに画像を載せる
  - 縦軸: 値段
  - 横軸: 日付
  - 描画したグラフは表示するだけで、一旦保存しないでOK
- 昨日に値段と比較して、変動結果を表示
  - 安くなってる or 高くなってる or 同じ

**Comment by kikudesuyo** [comment]
縦軸と横軸の値は.txtに羅列するっていう感じでOK?
あとどのような形でデータを入れるかを決める必要がありそうです。
